### PR TITLE
added readme file for apache setup

### PR DESCRIPTION
**Pull request by abhishekjhaji**

### CODE REVIEW

**Comment by abhishekjhaji** [comment]
Hey @alexisduque 

I changed it to be able to open it in my IDE. Do you need mode of those 3 files to be reverted? Any specific reasons?

**Comment by alexisduque** [comment]
Just because it's a _best practise_ to avoid versioning useless changes.
But it's just a detail, don't worry :smirk:

**Comment by alexisduque** [comment]
Merged. Thanks @abhishekjhaji ! :smile:

**Comment by abhishekjhaji** [comment]
Oh ok. Will keep in mind from next time. :)

**Pull request merged**
